### ISSUE TITLE
google-python-cloud-debugger unavailable for Python 3.7

### ISSUE THREAD

**Issue by SubtleMetaphor** [GoogleCloudPlatform/cloud-debug-python#20]
The google-python-cloud-debugger package is not available for python 3.7. When you try to install it, you get:

```
ERROR: Could not find a version that satisfies the requirement google-python-cloud-debugger (from versions: none)
ERROR: No matching distribution found for google-python-cloud-debugger
```

Just following the instructions here:
https://cloud.google.com/debugger/docs/setup/python

Will NOT work for Python 3.7. 

I have added "google-python-cloud-debugger" to requirements.txt, and added this code to main.py:

```
try:
    import googleclouddebugger
    googleclouddebugger.enable()
except ImportError:
    pass
```

Yet, the application will not be possible to debug in GAE. Probably because even GAE is unable to install that package on the platform!

**Comment by SubtleMetaphor** [comment]
Thanks for the reply.

I'm not sure what's causing this. I'm using the standard environment for a Django 3.0 app. According to google cloud platform debugger (deployed files) This is my main.py:

```
try:
    import googleclouddebugger
    googleclouddebugger.enable()
except ImportError:
    pass

from mysite.wsgi import application

# App Engine by default looks for a main.py file at the root of the app
# directory with a WSGI-compatible object called app.
# This file imports the WSGI-compatible object of your Django app,
# application from mysite/wsgi.py and renames it app so it is discoverable by
# App Engine without additional configuration.
# Alternatively, you can add a custom entrypoint field in your app.yaml:
# entrypoint: gunicorn -b :$PORT mysite.wsgi
app = application
```

I did try putting that code in manage.py instead, but it didn't make a difference.

And this is my requirements:
```
asgiref==3.2.3
cachetools==4.0.0
certifi==2019.11.28
chardet==3.0.4
Django==3.0.6
django-cleanup==4.0.0
django-storages==1.9.1
django-taggit==1.2.0
google-api-core==1.16.0
google-auth==1.11.3
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0
idna==2.9
Markdown==3.2.1
mysqlclient==1.4.6
patreon==0.5.0
protobuf==3.11.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-dateutil==2.8.1
pytz==2019.3
redis==3.4.1
requests==2.23.0
rsa==4.0
six==1.14.0
sqlparse==0.3.0
urllib3==1.25.8
google-python-cloud-debugger
gunicorn
```

Yet GAE says it isn't properly setup for debugging:
![](https://i.gyazo.com/8f396c333af6d99b7f16af35df9c7699.png)

Other than this problem, the app is working just fine.

**Comment by di** [comment]
Is your application up and running? Usually this happens when the instance has been scaled down, so there are no active debug targets. Try sending it a few requests and clicking the "Try again" button below that warning.

**Comment by SubtleMetaphor** [comment]
Yeah, the application is up and running. I tried browsing around on it, causing several requests, and clicking retry. No avail.

Does it need a substantial amount of traffic before debugging becomes available?

**Comment by di** [comment]
No, should be only a single request. I was able to reproduce this with my example, and making a single request enabled the debugger.

Is it possible that you have a custom entrypoint and your `main.py` file is not actually being used? What's the contents of your `app.yaml` file?

**Comment by SubtleMetaphor** [comment]
Ah, sorry, I should have included that.

Here's my app.yaml:
```
# [START django_app]
runtime: python37

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/
  secure: always

# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto
  secure: always
# [END django_app]
```

No custom entry point!
